// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyTinTucConsole;

#nullable disable

namespace QuanLyTinTucConsole.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250325015238_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyTinTucConsole.LoaiTinTuc", b =>
                {
                    b.Property<string>("MaLoai")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TenLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaLoai");

                    b.ToTable("LoaiTinTucs");

                    b.HasData(
                        new
                        {
                            MaLoai = "LT000001",
                            TenLoai = "Thể thao"
                        },
                        new
                        {
                            MaLoai = "LT000002",
                            TenLoai = "Du lịch"
                        },
                        new
                        {
                            MaLoai = "LT000003",
                            TenLoai = "Thời sự"
                        },
                        new
                        {
                            MaLoai = "LT000004",
                            TenLoai = "Quốc tế"
                        });
                });

            modelBuilder.Entity("QuanLyTinTucConsole.NhanVien", b =>
                {
                    b.Property<string>("MaTaiKhoan")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTaiKhoan");

                    b.ToTable("NhanViens");

                    b.HasData(
                        new
                        {
                            MaTaiKhoan = "NV000001",
                            DiaChi = "Hà Nội",
                            Email = "nguyenvana@example.com",
                            Ten = "Nguyễn Văn A",
                            VaiTro = "Admin"
                        },
                        new
                        {
                            MaTaiKhoan = "NV000002",
                            DiaChi = "TP.HCM",
                            Email = "tranthib@example.com",
                            Ten = "Trần Thị B",
                            VaiTro = "Editor"
                        },
                        new
                        {
                            MaTaiKhoan = "NV000003",
                            DiaChi = "Đà Nẵng",
                            Email = "levanc@example.com",
                            Ten = "Lê Văn C",
                            VaiTro = "Writer"
                        });
                });

            modelBuilder.Entity("QuanLyTinTucConsole.TinTuc", b =>
                {
                    b.Property<string>("MaTinTuc")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MaLoai")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NguoiDangTin")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("NoiDungTin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MaTinTuc");

                    b.HasIndex("MaLoai");

                    b.HasIndex("NguoiDangTin");

                    b.ToTable("TinTucs");

                    b.HasData(
                        new
                        {
                            MaTinTuc = "TT000001",
                            MaLoai = "LT000001",
                            NgayDang = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDangTin = "NV000001",
                            NoiDungTin = "Nội dung tin thể thao...",
                            TieuDe = "Trận đấu bóng đá tối nay"
                        },
                        new
                        {
                            MaTinTuc = "TT000002",
                            MaLoai = "LT000002",
                            NgayDang = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDangTin = "NV000002",
                            NoiDungTin = "Nội dung tin du lịch...",
                            TieuDe = "Khám phá Đà Lạt mùa hoa"
                        },
                        new
                        {
                            MaTinTuc = "TT000003",
                            MaLoai = "LT000003",
                            NgayDang = new DateTime(2025, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NguoiDangTin = "NV000003",
                            NoiDungTin = "Nội dung tin thời sự...",
                            TieuDe = "Tin tức thời sự mới nhất"
                        });
                });

            modelBuilder.Entity("QuanLyTinTucConsole.TinTuc", b =>
                {
                    b.HasOne("QuanLyTinTucConsole.LoaiTinTuc", "LoaiTinTuc")
                        .WithMany("TinTucs")
                        .HasForeignKey("MaLoai")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("QuanLyTinTucConsole.NhanVien", "NhanVien")
                        .WithMany("TinTucs")
                        .HasForeignKey("NguoiDangTin")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiTinTuc");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("QuanLyTinTucConsole.LoaiTinTuc", b =>
                {
                    b.Navigation("TinTucs");
                });

            modelBuilder.Entity("QuanLyTinTucConsole.NhanVien", b =>
                {
                    b.Navigation("TinTucs");
                });
#pragma warning restore 612, 618
        }
    }
}
